window.SNIPPET_CATEGORIES = {
  "categories": [
    "Ethics",
    "Thinkers",
    "Gov",
    "Society",
    "Public Service",
    "Theory Answers",
    "Case Studies",
    "Introductions",
    "Conclusions",
    "Quotes Bank"
  ],
  "ranks": [
    "Quotes Bank",
    "RANK 1 SHRUTI SHARMA",
    "RANK 111 KASHISH KALRA",
    "RANK 156 ZINNIA AURORA",
    "RANK 210 SANIA SEERVI",
    "RANK 37 SHOBHIKA PATHAK",
    "RANK 50 K N CHANDANA JAHNAVI",
    "RANK 9 NAUSHEEN",
    "RANK 289 CHANDAR PRABHA SHARMA",
    "RANK 399 OISHEE MANDAL",
    "RANK 100 VIJETA B HOSAMANI",
    "RANK 127 ADITI UPADHYAY",
    "RANK 189 POORVA AGRAWAL",
    "RANK 194 ADITI YADAV",
    "RANK 199 TRIPTI KALHANS",
    "RANK 204 SHUBHRA PANDA",
    "RANK 99 ANNAPURNA SINGH",
    "RANK 25 RITIKA VERMA",
    "RANK 26 RUPAL RANA",
    "RANK 36 AYUSHI PRADHAN",
    "RANK 39 DEEPTI ROHILLA",
    "RANK 51 RAJPUT NEHA UDDHAVSINGH",
    "RANK 17 SWATI SHARMA",
    "RANK 61 KHUSHHALI SOLANKI",
    "RANK 65 CHHAYA SINGH",
    "RANK 80 GARIMA MUNDRA",
    "RANK 18 WARDAH KHAN",
    "RANK 263 GIRISHA CHAUDHARY",
    "RANK 1 SHAKTI DUBEY",
    "RANK 189 ANUPRIYA RAI",
    "RANK 40 IRAM CHOUDHARY",
    "RANK 7 AAYUSHI BANSAL"
  ],
  "years": [
    "All them",
    "2021",
    "2022",
    "2023",
    "2024",
    "2025",
    "2026"
  ],
  "papers": [
    "Your Choice",
    "Essay",
    "GS Paper 1",
    "GS Paper 2",
    "GS Paper 3",
    "Ethics",
    "PUB ADD"
  ]
};